name: C# Deployment

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Stop server
        run: appcmd stop sites "TicketSlave"
        
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --logger trx --results-directory "TestResults"
        
      - name: Install npm dependencies
        working-directory: ./angularapp
        run: npm install
        
      - name: Publish release
        run: dotnet publish webapi --configuration Release -o C:\inetpub\wwwroot\ticketslave

      - name: Start server
        run: appcmd start sites "TicketSlave"

