name: C# Lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            4.7.2
            7.0.403

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run C# linter (e.g., StyleCop, Roslyn Analyzers, etc.)
        run: dotnet analyze webapi
        
      - name: Test
        run: dotnet test --no-build --verbosity normal